# Generated by Django 4.1.5 on 2023-01-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TempSensor',
            fields=[
                ('basesensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_api.basesensor')),
                ('unit', models.CharField(choices=[('c', '°C'), ('k', 'K')], max_length=5)),
            ],
            bases=('sensor_api.basesensor',),
        ),
    ]
