# Generated by Django 4.1.5 on 2023-01-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowSensor',
            fields=[
                ('basesensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_api.basesensor')),
                ('unit', models.CharField(choices=[('lpm', 'l/min'), ('lph', 'l/h')], max_length=5)),
            ],
            bases=('sensor_api.basesensor',),
        ),
    ]
