# Generated by Django 4.1.5 on 2023-01-07 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0003_humiditysensor_pressuresensor_rotationsensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesensor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basesensor',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
