# Generated by Django 4.1.5 on 2023-01-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0004_basesensor_created_basesensor_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandBaseString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(default='python3 obd.py {command} {args}', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('command', models.CharField(max_length=250)),
                ('args', models.CharField(max_length=250)),
                ('base_string', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor_api.commandbasestring')),
            ],
        ),
    ]
