# Generated by Django 4.1.5 on 2023-01-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0005_commandbasestring_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesensor',
            name='command',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sensor_api.command'),
        ),
    ]
