# Generated by Django 4.1.5 on 2023-01-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0006_alter_basesensor_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesensor',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor_api.command'),
        ),
    ]
