# Generated by Django 4.1.5 on 2023-01-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0007_alter_basesensor_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='command',
        ),
        migrations.AlterField(
            model_name='command',
            name='args',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
