# Generated by Django 4.1.5 on 2023-01-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0008_remove_command_command_alter_command_args_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='base_string',
            new_name='base',
        ),
        migrations.AlterField(
            model_name='commandbasestring',
            name='string',
            field=models.CharField(default='python3 obd.py {args}', max_length=200),
        ),
    ]
