# Generated by Django 4.1.5 on 2023-01-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0009_rename_base_string_command_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesensor',
            name='pin_number',
        ),
        migrations.RemoveField(
            model_name='command',
            name='args',
        ),
        migrations.AddField(
            model_name='basesensor',
            name='command_args',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
