# Generated by Django 4.1.5 on 2023-01-08 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0010_remove_basesensor_pin_number_remove_command_args_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesensor',
            name='command',
        ),
        migrations.AddField(
            model_name='basesensor',
            name='command_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sensor_api.commandbasestring'),
        ),
        migrations.DeleteModel(
            name='Command',
        ),
    ]
