# Generated by Django 4.1.5 on 2023-01-08 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0011_remove_basesensor_command_basesensor_command_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandbasestring',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandbasestring',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
