# Generated by Django 4.1.5 on 2023-01-08 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0012_commandbasestring_created_commandbasestring_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesensor',
            name='command_args',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='basesensor',
            name='command_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sensor_api.commandbasestring'),
        ),
    ]
