# Generated by Django 4.1.5 on 2023-01-08 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0013_alter_basesensor_command_args_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('basesensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_api.basesensor')),
                ('unit', models.CharField(choices=[('c', '°C'), ('k', 'K'), ('lpm', 'l/min'), ('lph', 'l/h'), ('rpm', 'r/m'), ('dpm', 'deg/m'), ('rel', '%'), ('abs', 'g/kg'), ('kph', 'km/h'), ('mph', 'mi/h'), ('bar', 'bar'), ('psi', 'psi'), ('kpa', 'kPa')], max_length=5)),
            ],
            bases=('sensor_api.basesensor',),
        ),
        migrations.RemoveField(
            model_name='humiditysensor',
            name='basesensor_ptr',
        ),
        migrations.RemoveField(
            model_name='pressuresensor',
            name='basesensor_ptr',
        ),
        migrations.RemoveField(
            model_name='rotationsensor',
            name='basesensor_ptr',
        ),
        migrations.RemoveField(
            model_name='speedsensor',
            name='basesensor_ptr',
        ),
        migrations.RemoveField(
            model_name='tempsensor',
            name='basesensor_ptr',
        ),
        migrations.DeleteModel(
            name='FlowSensor',
        ),
        migrations.DeleteModel(
            name='HumiditySensor',
        ),
        migrations.DeleteModel(
            name='PressureSensor',
        ),
        migrations.DeleteModel(
            name='RotationSensor',
        ),
        migrations.DeleteModel(
            name='SpeedSensor',
        ),
        migrations.DeleteModel(
            name='TempSensor',
        ),
    ]
