# Generated by Django 4.1.5 on 2023-01-15 13:21

from django.db import migrations, models
import sensor_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_api", "0014_sensor_remove_humiditysensor_basesensor_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandbasestring",
            name="string",
            field=models.CharField(
                default="python3 obd.py {args}",
                max_length=200,
                validators=[sensor_api.validators.validate_command_base_string],
            ),
        ),
    ]
