# Generated by Django 4.1.5 on 2023-01-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_api", "0015_alter_commandbasestring_string"),
    ]

    operations = [
        migrations.CreateModel(
            name="OBDSensor",
            fields=[
                (
                    "basesensor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sensor_api.basesensor",
                    ),
                ),
            ],
            bases=("sensor_api.basesensor",),
        ),
        migrations.RenameModel(
            old_name="Sensor",
            new_name="OneWireSensor",
        ),
    ]
