# Generated by Django 4.1.5 on 2023-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_api", "0019_obdsensor_sensor_oid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basesensor",
            name="unit",
            field=models.CharField(
                choices=[
                    ("c", "°C"),
                    ("k", "K"),
                    ("lpm", "l/min"),
                    ("lph", "l/h"),
                    ("rpm", "r/m"),
                    ("dpm", "deg/m"),
                    ("rel", "%"),
                    ("abs", "g/kg"),
                    ("kph", "km/h"),
                    ("mph", "mi/h"),
                    ("bar", "bar"),
                    ("psi", "psi"),
                    ("kpa", "kPa"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
