# Generated by Django 4.1.5 on 2023-01-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_api", "0020_alter_basesensor_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basesensor",
            old_name="command_args",
            new_name="address",
        ),
        migrations.AlterField(
            model_name="basesensor",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("c", "°C"),
                    ("k", "K"),
                    ("lpm", "l/min"),
                    ("lph", "l/h"),
                    ("rpm", "r/m"),
                    ("dpm", "deg/sec"),
                    ("rel", "%"),
                    ("abs", "g/kg"),
                    ("kph", "km/h"),
                    ("mph", "mi/h"),
                    ("bar", "bar"),
                    ("psi", "psi"),
                    ("kpa", "kPa"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
